spring:
  output:
    ansi:
      enabled: always
  application:
    name: fitpower-app
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitpower_db?serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: rootpass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

logging:
  level:
    root: info